### ISSUE TITLE
fix:An error messages appear on Sign up page

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#225] opened 2024-08-28 11:02 UTC
### Describe your issue

An error messages appear on Sign up page when try to open this page

### Steps to reproduce

1. Go to http://bebalance.eu-central-1.elasticbeanstalk.com/sign-up
2. Pay attention to the error messages that appear

### What was the actual result?

An error messages appeared

### What was the expected result?

An error messages dosn't appear

### Put here any screenshots or videos (optional)

![2024-08-28_11h52_38](https://github.com/user-attachments/assets/1cde65a8-c6ff-4261-ba0f-16daad99eb9f)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by LiudmylaPerev** [comment] 2024-08-28 12:22
duplicate of ticket[#222](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/222)

**Closed** 2024-08-28 12:23 UTC
Labels: bug, frontend
